version: '3.8'

services:

  java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
    working_dir: /app
